### PR TITLE
Geiger version

### PR DESCRIPTION
**Pull request by hpsaturn**
## Description

Firmware implementation and support the CanAirIO Sensorslib with Geiger sensor CAJOE support

## Tests

- [x] tested in real hardware
- [x] backward compatibility tests
- [x] enable sensor via sensors setter
- [x] validate cloud payload (HA MQTT)
- [x] add sensorlib example
- [x] values over Bluetooth
- [x] values over InfluxDB
- [ ] official documentation 

## Credits

Thanks to @roberbike @iw2lsi for the tests and first implementation.

### CODE REVIEW

**Review by roberbike — APPROVED** [review]

**Comment by hpsaturn** [comment]
I synced it to the last version of Sensorlib and CanAirIO firmware, in order to try to have this PR in the next release. Also we have a new suppor for floats numbers in the TFT screen, regarding that I removed some extra code that we had in the main. Please try to test that in your Geiger sensors.. Thanks in advance.

**Comment by roberbike** [comment]
> I synced it to the last version of Sensorlib and CanAirIO firmware, in order to try to have this PR in the next release. Also we have a new suppor for floats numbers in the TFT screen, regarding that I removed some extra code that we had in the main. Please try to test that in your Geiger sensors.. Thanks in advance.

Tested with AM2320 + esp32-WROOM + OLED. Works fine.
image

**Comment by iw2lsi** [comment]
Hi...

   thanks for the great job... I'll test it ASAP

         Giampaolo


Il giorno lun 10 lug 2023 alle ore 18:48 roberbike ***@***.***>
ha scritto:

**Comment by hpsaturn** [comment]
I did some refactors in the Sensorlib code, and added new setter on the library to enable the Geiger sensor. Please confirm if this version is working. 

https://github.com/kike-canaries/canairio_firmware/assets/423856/eaa7a607-c3d5-4290-b51e-3c1a1604f2e9

**Comment by roberbike** [comment]
Ver 957 does not show RAD and CPM values, but clicks are counted well. Tested in oled version.
image

**Comment by hpsaturn** [comment]
I released a new version on the OTA testing channel with a possible fix. Also with a some fixes on HA cloud file. Thanks in advance for testing it in the real hardware :)

**Pull request merged**
